image: umbrellium/sphinx-doc

pages:
  script:
  - apt-get update
  - apt-get -y install dvipng
  - pip install codespell
  - READTHEDOCS=True sphinx-build -nWT -b html . _build/html
  - mv _build/html/ public/
  - codespell --skip=".git,_static,_build,Diff*" --quiet-level=2
  artifacts:
    paths:
    - public
  only:
  - master
  - merge_requests
