image: umbrellium/sphinx-doc

spelling:
  script:
  - pip install codespell
  - codespell --skip=".git,_static,_build,Diff*" --quiet-level=2
  only:
  - master
  - merge_requests

orphans:
  script:
  - find ./ -name "*.rst"|xargs -i grep -H orphan {}
  - if [ $(find ./ -name "*.rst"|xargs -i grep -H orphan {}|wc -l) -gt "1" ]; then $(exit 1); else $(exit 0); fi
  only:
  - master

pages:
  script:
  - apt-get update
  - apt-get -y install dvipng
  - pip install pygments --upgrade 
  - READTHEDOCS=True sphinx-build -nWT -b html . _build/html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  - merge_requests
