image: cloudcompass/docker-rtdsphinx

spelling:
  script:
  - pip3 install codespell
  - codespell --skip=".git,_static,_build,Diff*,*.patch,*.f90" --quiet-level=2 --ignore-words-list="adress,catalogue,noe,soler"
  only:
  - master
  - merge_requests

lint:
  script:
  - pip3 install doc8
  - git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA
  # Run linter over files in last commit (not really good enough, want all files in MR but can't do that)
  - ( set -e; for file in $(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA); do doc8 --max-line-length 120 $file; done )
  only:
  - merge_requests
  - master

orphans:
  script:
  # Report all the orphans but ignore the exit code
  - find ./ -name "*.rst"|xargs -i grep -H orphan {} || true
  # Now handle the error code
  - if [ $(find ./ -name "*.rst"|xargs -i grep -H orphan {}|wc -l) -gt "2" ]; then $(exit 1); else $(exit 0); fi
  only:
  - master

pages:
  script:
  - apt-get -y install dvipng
  - pip3 install pygments --upgrade
  - pip3 install Sphinx --upgrade
  - pip3 install sphinx-rtd-theme --upgrade
  - READTHEDOCS=True sphinx-build -nWT -b html . _build/html
  - mv _build/html/ public/
  - echo -e "\n\n\e[1mYou can find your build of this documentation at \n\t\e[32m${CI_PAGES_URL}\e[0m\n\n"
  artifacts:
    paths:
    - public
  only:
  - master
  - merge_requests
