image: umbrellium/sphinx-doc

pages:
  script:
  - apt-get update
  - apt-get -y install dvipng
  - READTHEDOCS=True sphinx-build -nWT -b html . _build/html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
