image: plaindocs/docker-sphinx

pages:
  script:
  - sudo apt-get -y install dvipng
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade sphinx
  - make html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
